const user_json = [
  {
    "id": 0,
    "picture": "http://placehold.it/32x32",
    "age": 20,
    "name": "Martinez Prince",
    "gender": "male",
    "email": "martinezprince@terrasys.com",
    "password": "5db1bebdc22559dbbfff2b3b",
    "phone": "+971 (828) 509-2892",
    "street": "209 Balfour Place, Linwood, Arizona, 9647",
    "city": "Kersey",
    "state": "Virginia",
    "country": "Viet Nam",
    "about_me": "Elit anim laborum ut aliqua cupidatat Lorem eu eu proident sint cillum minim reprehenderit. Velit et et velit nostrud anim. Esse sint id quis laborum labore ut sunt exercitation labore eu mollit dolore. Nisi anim do pariatur quis duis labore deserunt minim incididunt.\r\n",
    "verified_email": 0,
    "verified_phone": 0,
    "latitude": 65.155827,
    "longitude": -160.861496
  },
  {
    "id": 1,
    "picture": "http://placehold.it/32x32",
    "age": 37,
    "name": "Elma Luna",
    "gender": "female",
    "email": "elmaluna@terrasys.com",
    "password": "5db1bebd229d2f867e5f52d2",
    "phone": "+971 (928) 422-2668",
    "street": "276 Jodie Court, Stockwell, Alabama, 1948",
    "city": "Allentown",
    "state": "New Jersey",
    "country": "Botswana",
    "about_me": "Cupidatat consectetur qui minim ullamco. Aliqua ut id ex dolor do voluptate aute consequat Lorem. Ad nisi cillum irure minim quis minim.\r\n",
    "verified_email": 1,
    "verified_phone": 0,
    "latitude": -19.425829,
    "longitude": 21.39951,
  },
  {
    "id": 2,
    "picture": "http://placehold.it/32x32",
    "age": 36,
    "name": "Dionne Forbes",
    "gender": "female",
    "email": "dionneforbes@terrasys.com",
    "password": "5db1bebda9c1943b85a243d0",
    "phone": "+971 (924) 439-2231",
    "street": "887 Lincoln Road, Hatteras, Delaware, 2651",
    "city": "Faywood",
    "state": "Nebraska",
    "country": "Denmark",
    "about_me": "Eu nostrud exercitation dolor dolore elit nisi in nostrud duis sit voluptate aliquip et. Ipsum dolor quis pariatur ut laboris sit id proident eu minim magna voluptate commodo. Deserunt elit mollit labore laboris cupidatat irure irure consectetur. Aliquip et laboris voluptate ullamco culpa do Lorem et Lorem mollit cupidatat.\r\n",
    "verified_email": 1,
    "verified_phone": 0,
    "latitude": 30.594184,
    "longitude": -27.096124,
  },
  {
    "id": 3,
    "picture": "http://placehold.it/32x32",
    "age": 36,
    "name": "Stuart Vega",
    "gender": "male",
    "email": "stuartvega@terrasys.com",
    "password": "5db1bebdfbb38fd6b8051cd5",
    "phone": "+971 (806) 457-2109",
    "street": "568 Amersfort Place, Tooleville, Oregon, 560",
    "city": "Woodruff",
    "state": "Maryland",
    "country": "Mauritania",
    "about_me": "Non pariatur laboris commodo eu deserunt excepteur sint magna do. Est sint tempor nostrud in sit minim labore dolor laborum culpa. Reprehenderit amet mollit tempor ullamco eu officia ea ut. Id veniam aliqua laborum mollit voluptate officia cillum eiusmod deserunt qui sunt dolor. Mollit commodo exercitation voluptate eiusmod qui ipsum ea in Lorem incididunt do cillum.\r\n",
    "verified_email": 0,
    "verified_phone": 0,
    "latitude": -71.6082,
    "longitude": -92.866695,
  },
  {
    "id": 4,
    "picture": "http://placehold.it/32x32",
    "age": 20,
    "name": "Padilla Lopez",
    "gender": "male",
    "email": "padillalopez@terrasys.com",
    "password": "5db1bebdac142bb486a837f2",
    "phone": "+971 (816) 499-3200",
    "street": "161 Crescent Street, Blandburg, Utah, 5343",
    "city": "Navarre",
    "state": "New Hampshire",
    "country": "Qatar",
    "about_me": "Excepteur proident nisi nostrud occaecat cupidatat adipisicing elit officia voluptate. Anim voluptate sunt non duis aliquip enim nisi. Velit elit aute ea ullamco sit irure reprehenderit nostrud ad. Consequat fugiat veniam enim duis non irure fugiat. Consequat sit aliquip velit in magna. Id exercitation labore non eiusmod deserunt aliqua ad nisi ea id duis laboris anim. Ullamco eiusmod veniam magna nulla laborum aliquip voluptate nulla amet.\r\n",
    "verified_email": 1,
    "verified_phone": 1,
    "latitude": 72.504729,
    "longitude": 91.286743
  },
  {
    "id": 5,
    "picture": "http://placehold.it/32x32",
    "age": 34,
    "name": "Houston Bradley",
    "gender": "male",
    "email": "houstonbradley@terrasys.com",
    "password": "5db1bebdb28a9246853aa4f3",
    "phone": "+971 (829) 491-2073",
    "street": "709 Village Road, Omar, Texas, 2569",
    "city": "Cassel",
    "state": "North Carolina",
    "country": "Kazakhstan",
    "about_me": "Incididunt magna cupidatat excepteur pariatur sint exercitation ipsum pariatur laboris. Occaecat fugiat proident irure proident aliquip consequat ullamco reprehenderit magna commodo. Irure exercitation consectetur ut sint Lorem sit id et. Minim et dolor magna id ullamco esse minim adipisicing. Aliqua incididunt mollit sit labore. Magna aliqua Lorem aute eu id veniam ipsum occaecat deserunt minim. Consectetur sunt quis ipsum velit quis sit exercitation mollit sit ex elit commodo tempor.\r\n",
    "verified_email": 0,
    "verified_phone": 1,
    "latitude": 48.800784,
    "longitude": 144.786783
  },
  {
    "id": 6,
    "picture": "http://placehold.it/32x32",
    "age": 36,
    "name": "Arline Ruiz",
    "gender": "female",
    "email": "arlineruiz@terrasys.com",
    "password": "5db1bebd3a186170af5c38c6",
    "phone": "+971 (938) 523-2876",
    "street": "722 Neptune Court, Cresaptown, Michigan, 4426",
    "city": "Castleton",
    "state": "Maine",
    "country": "Togo",
    "about_me": "Laborum Lorem ad adipisicing deserunt cillum anim ad commodo commodo sunt. Incididunt id quis ad excepteur commodo enim quis aliqua culpa do Lorem minim duis ut. Dolor sint aute dolor esse ex commodo consectetur amet dolor sint exercitation. Non culpa ullamco esse eiusmod velit irure aute.\r\n",
    "verified_email": 0,
    "verified_phone": 0,
    "latitude": 35.064535,
    "longitude": 85.679123
  },
  {
    "id": 7,
    "picture": "http://placehold.it/32x32",
    "age": 24,
    "name": "Vinson Morgan",
    "gender": "male",
    "email": "vinsonmorgan@terrasys.com",
    "password": "5db1bebdd0eb0779ba3d708a",
    "phone": "+971 (956) 579-3843",
    "street": "840 Rockwell Place, Cartwright, Northern Mariana Islands, 566",
    "city": "Greenbackville",
    "state": "Mississippi",
    "country": "Svalbard and Jan Mayen Islands",
    "about_me": "Eu veniam eu fugiat proident consectetur ex ullamco. Officia eiusmod ut sint sint amet et irure duis. Elit est cillum ea aliqua nostrud magna. Sunt esse do Lorem in deserunt et. Voluptate eu non nostrud nisi pariatur ullamco et ipsum adipisicing sint consequat esse id. Ullamco in aute ullamco consequat ipsum ea. Lorem excepteur laborum dolor eiusmod fugiat Lorem ipsum tempor reprehenderit exercitation.\r\n",
    "verified_email": 0,
    "verified_phone": 0,
    "latitude": 62.196907,
    "longitude": -51.402433
  },
  {
    "id": 8,
    "picture": "http://placehold.it/32x32",
    "age": 30,
    "name": "Gutierrez Bates",
    "gender": "male",
    "email": "gutierrezbates@terrasys.com",
    "password": "5db1bebdab78afad3ecbe04f",
    "phone": "+971 (993) 463-3993",
    "street": "202 Clinton Street, Sexton, Georgia, 9150",
    "city": "Shaft",
    "state": "Iowa",
    "country": "Kuwait",
    "about_me": "Non qui qui eu velit Lorem amet ut adipisicing officia qui aliqua cillum velit mollit. Deserunt excepteur deserunt ex sit tempor labore aliqua adipisicing do aliqua sint. Voluptate aliqua officia sit sit irure aute nostrud duis incididunt ad nostrud quis id ad. Amet consequat minim elit anim id amet.\r\n",
    "verified_email": 0,
    "verified_phone": 1,
    "latitude": -42.553421,
    "longitude": -141.323717
  },
  {
    "id": 9,
    "picture": "http://placehold.it/32x32",
    "age": 38,
    "name": "Kirby Mcdaniel",
    "gender": "male",
    "email": "kirbymcdaniel@terrasys.com",
    "password": "5db1bebdfa1cd4c508a60048",
    "phone": "+971 (880) 448-2293",
    "street": "184 Celeste Court, Saddlebrooke, Massachusetts, 3197",
    "city": "Bath",
    "state": "Virgin Islands",
    "country": "Niger",
    "about_me": "Fugiat id est consectetur dolor occaecat Lorem nulla excepteur irure qui laborum adipisicing. Aute eu cillum sit esse dolor non esse veniam aute sint culpa. Sunt consequat dolore dolore deserunt eiusmod ullamco excepteur. Adipisicing quis aliqua est ea consectetur labore reprehenderit cupidatat elit enim. Laboris ullamco est magna consequat deserunt qui labore do ea esse culpa. Exercitation dolore magna proident deserunt culpa ipsum duis eu ullamco ut. Ad proident irure dolor labore cupidatat duis ut dolor id sint labore consequat.\r\n",
    "verified_email": 1,
    "verified_phone": 0,
    "latitude": -53.774218,
    "longitude": 47.425999
  },
  {
    "id": 10,
    "picture": "http://placehold.it/32x32",
    "age": 24,
    "name": "Barnett Pacheco",
    "gender": "male",
    "email": "barnettpacheco@terrasys.com",
    "password": "5db1bebd5614f9f4f53236d4",
    "phone": "+971 (932) 492-3051",
    "street": "770 Bergen Avenue, Bagtown, Alaska, 4657",
    "city": "Biehle",
    "state": "Minnesota",
    "country": "Paraguay",
    "about_me": "Ea cupidatat pariatur esse ipsum sit deserunt. Eiusmod aute nisi incididunt exercitation deserunt officia est amet nostrud duis non ipsum. Nulla aute eu consequat est consectetur voluptate amet. Reprehenderit excepteur occaecat exercitation culpa minim consectetur ut deserunt aliquip sit minim velit et id. Ad consequat quis cupidatat nisi sunt cillum cupidatat laboris sit aute do qui ea qui. Consequat minim elit fugiat irure. Eu in et fugiat minim Lorem et labore qui pariatur.\r\n",
    "verified_email": 0,
    "verified_phone": 1,
    "latitude": -25.232472,
    "longitude": 100.034604
  },
  {
    "id": 11,
    "picture": "http://placehold.it/32x32",
    "age": 21,
    "name": "Nanette Gallagher",
    "gender": "female",
    "email": "nanettegallagher@terrasys.com",
    "password": "5db1bebd9f9c464da2afd88e",
    "phone": "+971 (831) 580-3134",
    "street": "319 Dahlgreen Place, Tonopah, West Virginia, 1427",
    "city": "Buxton",
    "state": "Idaho",
    "country": "Tajikistan",
    "about_me": "Anim ut sit irure id ut aliqua qui ad reprehenderit magna id commodo id excepteur. Voluptate ea incididunt Lorem eiusmod exercitation et eu Lorem fugiat tempor minim nostrud fugiat. Consequat ea tempor nulla exercitation amet labore est reprehenderit duis et veniam culpa amet nisi. Aliqua nulla ad pariatur consectetur laborum laborum dolor voluptate esse esse. Pariatur est duis deserunt anim tempor laborum laboris minim occaecat minim Lorem nulla do.\r\n",
    "verified_email": 0,
    "verified_phone": 0,
    "latitude": -13.89628,
    "longitude": 168.131452
  },
  {
    "id": 12,
    "picture": "http://placehold.it/32x32",
    "age": 22,
    "name": "Sonia Rocha",
    "gender": "female",
    "email": "soniarocha@terrasys.com",
    "password": "5db1bebd0c9a3fab3a006a31",
    "phone": "+971 (873) 415-2331",
    "street": "274 Throop Avenue, Lisco, Kentucky, 7191",
    "city": "Lewis",
    "state": "Nevada",
    "country": "Germany",
    "about_me": "Excepteur reprehenderit ex officia velit quis laboris ut ut. Anim commodo eu consequat commodo minim pariatur est non dolor proident laboris reprehenderit ad. Sunt Lorem irure elit elit occaecat proident magna et consectetur Lorem eiusmod Lorem veniam. Est laborum nulla ipsum nisi laborum culpa cupidatat minim non non nostrud do amet. Eu veniam do veniam sunt irure eiusmod magna dolore enim Lorem. Consectetur cillum labore incididunt occaecat exercitation. Sint nostrud est id cillum nulla ut magna reprehenderit id ex minim.\r\n",
    "verified_email": 0,
    "verified_phone": 1,
    "latitude": 86.833672,
    "longitude": 100.668575
  },
  {
    "id": 13,
    "picture": "http://placehold.it/32x32",
    "age": 23,
    "name": "Gretchen Mcpherson",
    "gender": "female",
    "email": "gretchenmcpherson@terrasys.com",
    "password": "5db1bebdb19af07ff8e5f9ab",
    "phone": "+971 (837) 570-3836",
    "street": "438 Fillmore Place, Clay, Arkansas, 4894",
    "city": "Dellview",
    "state": "District Of Columbia",
    "country": "Korea (North)",
    "about_me": "Sunt id tempor ea excepteur velit duis labore adipisicing voluptate enim eiusmod non aute. Ullamco minim culpa ad magna. Anim elit voluptate laboris magna in occaecat sit dolore et dolore voluptate non velit. Irure labore voluptate consectetur dolor commodo voluptate fugiat voluptate aute adipisicing fugiat ipsum dolore. Pariatur commodo esse amet qui aute occaecat ex elit enim dolore ea aliqua dolore magna. In consectetur eiusmod reprehenderit duis deserunt anim id sit ex.\r\n",
    "verified_email": 0,
    "verified_phone": 1,
    "latitude": 78.042138,
    "longitude": -57.749619
  },
  {
    "id": 14,
    "picture": "http://placehold.it/32x32",
    "age": 23,
    "name": "Short Mcbride",
    "gender": "male",
    "email": "shortmcbride@terrasys.com",
    "password": "5db1bebda9ef3cb64060741a",
    "phone": "+971 (800) 555-3193",
    "street": "419 Dooley Street, Trona, Louisiana, 7874",
    "city": "Maplewood",
    "state": "Indiana",
    "country": "Slovak Republic",
    "about_me": "Enim nisi veniam ex ipsum irure nostrud ipsum adipisicing cillum commodo enim officia in sit. Proident id ad nisi voluptate duis culpa aute laboris. Non exercitation ex sunt sit sint.\r\n",
    "verified_email": 1,
    "verified_phone": 0,
    "latitude": 29.340174,
    "longitude": -124.550251
  },
  {
    "id": 15,
    "picture": "http://placehold.it/32x32",
    "age": 39,
    "name": "Abbott Cash",
    "gender": "male",
    "email": "abbottcash@terrasys.com",
    "password": "5db1bebd2f234c9a36659cd8",
    "phone": "+971 (905) 430-2110",
    "street": "296 Ellery Street, Slovan, Guam, 6792",
    "city": "Tedrow",
    "state": "Palau",
    "country": "Barbados",
    "about_me": "Nulla ex sit magna incididunt. Cupidatat sint nostrud labore enim irure. In ipsum laborum magna magna aliquip anim irure dolore elit ut. Magna aute quis pariatur nulla ullamco. Id tempor eu ex anim aliquip. Nostrud dolor aliquip in deserunt tempor officia ut tempor eiusmod elit dolor sit. Sit excepteur excepteur sit velit consequat est dolore excepteur quis consequat velit aliquip enim Lorem.\r\n",
    "verified_email": 1,
    "verified_phone": 0,
    "latitude": -6.812583,
    "longitude": -36.335665
  }
];

const user_permission_json = [
  {
    "id": 0,
    "user_id": 0,
    "role_id": 0
  },
  {
    "id": 1,
    "user_id": 1,
    "role_id": 2
  },
  {
    "id": 2,
    "user_id": 2,
    "role_id": 1
  },
  {
    "id": 3,
    "user_id": 3,
    "role_id": 2
  },
  {
    "id": 4,
    "user_id": 4,
    "role_id": 1
  },
  {
    "id": 5,
    "user_id": 5,
    "role_id": 2
  },
  {
    "id": 6,
    "user_id": 6,
    "role_id": 1
  }
];

const user_role_json = [
  {
    "id": 2,
    "role": "seller"
  },
  {
    "id": 1,
    "role": "customer",
  },
  {
    "id": 0,
    "role": "admin"
  }
];

const invalidate_token_json = [
  {
    "id": 0,
    "token": 0,
    "expires_in": "2019-04-08T11:25:43 -04:00"
  },
  {
    "id": 1,
    "token": 1,
    "expires_in": "2019-10-08T11:38:42 -04:00"
  },
  {
    "id": 2,
    "token": 2,
    "expires_in": "2019-04-03T10:44:45 -04:00",
    "updated_at": "2019-06-04T01:08:07 -04:00",
    "created_at": "2019-05-15T05:03:07 -04:00"
  },
  {
    "id": 3,
    "token": 3,
    "expires_in": "2019-10-10T04:24:01 -04:00",
    "updated_at": "2019-04-16T04:15:26 -04:00",
    "created_at": "2019-06-22T01:30:13 -04:00"
  },
  {
    "id": 4,
    "token": 4,
    "expires_in": "2019-03-16T04:31:16 -04:00",
    "updated_at": "2019-08-27T01:57:49 -04:00",
    "created_at": "2019-09-30T06:29:58 -04:00"
  }
];

module.exports = {
  user_json,
  user_permission_json,
  user_role_json,
  invalidate_token_json
}